site_name: My Docu
nav:
  - Home: index.md
  - API: api.md
theme:
  name: material
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
plugins:
  mkdocstrings:
    handlers:
      python:
        paths: [src]
          